name: Run gcr-cleaner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  gcr-cleaner:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCR_CLEANER_SA_KEY }}"

      - uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCR_CLEANER_SA_KEY }}

      - uses: "docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli"
        with:
          args: >-
            -repo=us-central1-docker.pkg.dev/bungie-api-webhooks/gcf-artifacts
            -recursive=true
            -tag-filter-any "^"
